# Generated by Django 5.2.4 on 2025-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_link_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
