# Generated by Django 5.2.4 on 2025-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_summaryfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
