# Generated by Django 5.2.4 on 2025-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
