# Generated by Django 5.2.4 on 2025-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_article_audio_url_article_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
